### PR TITLE
[#163] Add internal network traffic metrics

### PR DESCRIPTION
**Pull request by An-DJ**
Add new network traffic panels in the dashboard and the following metrics:
* pgagroal_network_sent
* pgagroal_network_received

Modify the spelling of some words in the dashboard.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Why not `_add(ssize_t)` ?

**Comment by An-DJ** [comment]
> Why not `_add(ssize_t)` ?

Yeah, it's a little bit more concise. I have modified the code just now.

**Comment by jesperpedersen** [comment]
Yeah, that looks better - maybe name them `network_sent` and `network_receive` in the function names as well

**Comment by jesperpedersen** [comment]
Also name the parameter, as

```
/**
* Increase network_sent
* @param s The size
* /
pgagroal_prometheus_network_sent(ssize_t s);
```

**Comment by An-DJ** [comment]
> Also name the parameter, as
> 
> ```
> /**
>  * Increase network_sent
>  * @param s The size
>  * /
> void pgagroal_prometheus_network_sent(ssize_t s);
> ```

Done.

**Comment by jesperpedersen** [comment]
Better do it in `prometheus.c` and the Grafana file as well

**Comment by An-DJ** [comment]
> Better do it in `prometheus.c` and the Grafana file as well

Done.

**Comment by jesperpedersen** [comment]
Thanks for your contribution !

**Pull request merged**
