### PR TITLE
Fix management

### PR DESCRIPTION
**Pull request by fluca1978**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
```
src/libpgagroal/configuration.c: In function ‘to_string’:
src/libpgagroal/configuration.c:3816:42: warning: ‘%s’ directive output may be truncated writing between 1 and 128 bytes into a region of size 127 [-Wformat-truncation=]
 3816 |          snprintf(where, MISC_LENGTH, "\"%s\"", value);
      |                                          ^~
src/libpgagroal/configuration.c:3816:10: note: ‘snprintf’ output between 4 and 131 bytes into a destination of size 128
 3816 |          snprintf(where, MISC_LENGTH, "\"%s\"", value);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libpgagroal/configuration.c:3812:41: warning: ‘%s’ directive output may be truncated writing between 1 and 128 bytes into a region of size 127 [-Wformat-truncation=]
 3812 |          snprintf(where, MISC_LENGTH, "'%s'", value);
      |                                         ^~
src/libpgagroal/configuration.c:3812:10: note: ‘snprintf’ output between 4 and 131 bytes into a destination of size 128
 3812 |          snprintf(where, MISC_LENGTH, "'%s'", value);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libpgagroal/configuration.c:3821:39: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
 3821 |       snprintf(where, MISC_LENGTH, "%s", value);
      |                                       ^
src/libpgagroal/configuration.c:3821:7: note: ‘snprintf’ output between 1 and 129 bytes into a destination of size 128
 3821 |       snprintf(where, MISC_LENGTH, "%s", value);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Can you fix these in this PR as well ?

**Comment by fluca1978** [comment]
Uhm, interesting, I'm not having such issues on my system with clang:

$ clang --version
clang version 13.0.1 (Red Hat 13.0.1-2.module+el8.6.0+987+d36ea6a1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin


and I was curious about what the failure was. Did you updated the build process?
I've placed a single commit to handle the right size of the string in
the to_string function, which has not been touched in this PR.
Can you check and decide if the commit has to be squashed or moved
back in the commit history?

Luca

**Comment by jesperpedersen** [comment]
GCC 12
```
src/libpgagroal/configuration.c: In function ‘to_string’:
src/libpgagroal/configuration.c:3816:46: warning: ‘%s’ directive output may be truncated writing between 1 and 128 bytes into a region of size 124 [-Wformat-truncation=]
 3816 |          snprintf(where, MISC_LENGTH - 3, "\"%s\"", value);
      |                                              ^~
src/libpgagroal/configuration.c:3816:10: note: ‘snprintf’ output between 4 and 131 bytes into a destination of size 125
 3816 |          snprintf(where, MISC_LENGTH - 3, "\"%s\"", value);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libpgagroal/configuration.c:3812:45: warning: ‘%s’ directive output may be truncated writing between 1 and 128 bytes into a region of size 124 [-Wformat-truncation=]
 3812 |          snprintf(where, MISC_LENGTH - 3, "'%s'", value);
      |                                             ^~
src/libpgagroal/configuration.c:3812:10: note: ‘snprintf’ output between 4 and 131 bytes into a destination of size 125
 3812 |          snprintf(where, MISC_LENGTH - 3, "'%s'", value);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libpgagroal/configuration.c:3821:41: warning: ‘%s’ directive output may be truncated writing up to 128 bytes into a region of size 127 [-Wformat-truncation=]
 3821 |       snprintf(where, MISC_LENGTH - 1, "%s", value);
      |                                         ^~
src/libpgagroal/configuration.c:3821:7: note: ‘snprintf’ output between 1 and 129 bytes into a destination of size 127
 3821 |       snprintf(where, MISC_LENGTH - 1, "%s", value);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

clang 15
```
src/libpgagroal/configuration.c:3578:7: error: statement requires expression of integer type ('atomic_schar' (aka '_Atomic(signed char)') invalid)
      switch (state)
      ^       ~~~~~
```

**Comment by jesperpedersen** [comment]
You could use `pgagroal_append()` as well...

**Comment by brettgoss** [comment]
@jesperpedersen I'm getting those make errors as well on the latest master after you introduced 61d60f2d86d6b61a05a1412aff51f3077216221a. I don't think they're specific to this branch. 

There doesn't seem to be an existing issue for this that I could find, but dropping 61d60f2d86d6b61a05a1412aff51f3077216221a allows me to build pgagroal again.

**Comment by jesperpedersen** [comment]
@brettgoss Yeah, they are on `master` with new functionality in the up-coming 1.6 release. They will be fixed before the release = for now it is a pointer to @fluca1978 with his work

**Comment by jesperpedersen** [comment]
We may have to compile with both gcc and clang in order to catch as many errors as we can...

**Comment by fluca1978** [comment]
We could apply, in the meantime, 7b6f7eefe13cbcc8f3946fc54b2ca9cd2f09e5ab to master since it should fix the compiler errors.

**Comment by jesperpedersen** [comment]
Personally, I would nuke all `s[n]print` usage and use `pgagroal_append` instead...

**Comment by fluca1978** [comment]
@jesperpedersen  I'm not able to find any `pgagroal_append` function, there is static `append` function into the prometheus stuff, I suspect you are referring to that.
In the meanwhile I managed to change the `to_string` function adding a size parameter so that it is now possible to manage and prevent overflows. I've also finally found a way to compile with gcc12, so we are now fine with this PR.

**Comment by jesperpedersen** [comment]
I fixed the atomic part, squashed and merged.

Thanks for your contribution !

**Comment by jesperpedersen** [comment]
I made append public, and use it to fix the process title warning.

CI is happy now with both gcc and clang

**Comment by vikingUnet** [comment]
Hello!
The same error:
```
/root/pgagroal/src/admin.c:535:39: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]
  535 |    snprintf(line, sizeof(line), "%s:%s", username, encoded);
      |                                       ^
In file included from /usr/include/stdio.h:867,
                 from /usr/include/openssl/crypto.h:20,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from /root/pgagroal/src/include/pgagroal.h:45,
                 from /root/pgagroal/src/admin.c:30:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 129) into a destination of size 128
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/pgagroal/src/admin.c: In function ‘update_user’:
/root/pgagroal/src/admin.c:704:45: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]
  704 |          snprintf(line, sizeof(line), "%s:%s", username, encoded);
      |                                             ^
In file included from /usr/include/stdio.h:867,
                 from /usr/include/openssl/crypto.h:20,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from /root/pgagroal/src/include/pgagroal.h:45,
                 from /root/pgagroal/src/admin.c:30:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 129) into a destination of size 128
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/pgagroal-admin-bin.dir/build.make:63: src/CMakeFiles/pgagroal-admin-bin.dir/admin.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: src/CMakeFiles/pgagroal-admin-bin.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by jesperpedersen** [comment]
@vikingUnet What is your compiler version ?

**Pull request closed without merging**
