### PR TITLE
enh: use `calloc(3)` instead of `malloc(3)` and `memset(3)`

### PR DESCRIPTION
**Pull request by SudeepRed**
This PR solves https://github.com/agroal/pgagroal/issues/312 and #190 
`calloc(3)` documentation: https://linux.die.net/man/3/calloc

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Make sure, that the pull request is rebased and squashed

**Comment by SudeepRed** [comment]
rebased and squashed!

**Comment by jesperpedersen** [comment]
Run `uncrustify` and squash the commits

**Comment by SudeepRed** [comment]
Finally, rebased and squashed!

**Comment by jesperpedersen** [comment]
Rebased, `uncrustify` and merged.

Thanks for your contribution !

**Pull request closed without merging**
