### PR TITLE
[#159] Add new pool metric pgagroal_tx_count and `Transaction rate` panel

### PR DESCRIPTION
**Pull request by An-DJ**
# Issue
#159 

# Task
* Add `pgagroal_tx_count ` which characterizes the number of transactions.
* Add new panel `Transaction rate` in Grafana dashboard,

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Looks good, but you have to only count the `I` to `T` transition - as the `T` to `E` transition is the same transaction

**Comment by jesperpedersen** [comment]
Looks good, but you have to only count the `I` to `T` transition - as the `T` to `E` transition is the same transaction

**Comment by An-DJ** [comment]
> Looks good, but you have to only count the `I` to `T` transition - as the `T` to `E` transition is the same transaction

@jesperpedersen I have checked my code and found that it only count the `I` to `T` transaction. : )

Perhaps you misunderstood something?

**Comment by jesperpedersen** [comment]
Yeah, I read it wrong, sorry.

Thanks for your contribution !

**Pull request merged**
