### PR TITLE
Admin master key wrong message

### PR DESCRIPTION
**Pull request by fluca1978**
While using `pgagroal-admin` I found some odd cases that could be improved:
- warn the user when the inserted password is not valid, otherwise the user will see `Master Key` on the screen without any hint;
- print out where the vault is stored
- catch SIGINT during the insertion of the master key.

Since I'm not a day-by-day C developer, please review carefully.

### CODE REVIEW

**Comment by fluca1978** [comment]
I've done a few changes. In the beginning I deleted the `is_valid_password`, but after that I realized that having a function that do checks, not only about length, but about quality, would be useful. Therefore, I split `CHARS` into its part and created `do_check_master_key` to check the quality of the master key password.
Then, I refactored the generating function to use the concatenation of all the parts as the old `CHARS`.
The only part that remains, if we want, is to force the generation to validate the password, or better, to extract at least one char from every piece.

In the cae you want to integrate, squash or cherry pick.

**Comment by fluca1978** [comment]
Ok, added also the capability to automatically generate a password picking different set of chars, so that it will always contain numbers, letters, specials, and so on.

**Comment by jesperpedersen** [comment]
An earlier commit remove all password strength checking for user based account - leaving it to the DBA to set the guidelines. So, I think we should do the same in this case. And, hence `CHARS` is only going to be used for generated keys.

**Comment by jesperpedersen** [comment]
Yeah, the cherry-pick looks like it, but I would like to have a proper pull request for it, so rebase, fix indentation and squash, please :)

**Comment by fluca1978** [comment]
Opened issue #206. I'm closing this one and opening a new pull request since most of the work done here is not accepted.

**Pull request closed without merging**
